### ISSUE TITLE
Strict mode should be the default mode

### ISSUE THREAD

**Issue by jakubklimek** [malyvoj3/csvw-validator#24]
What is now called the Strict mode should be the default mode. There can be a "relaxed" mode, but since the Strict mode only displays warnings anyway, I do not see the use for it. If you insist on having two modes, then the Strict (default) mode should report bad encoding, missing schema, bad line endings etc. as errors, and the relaxed mode as warnings.

**Comment by malyvoj3** [comment]
Stric mode is now enabled everywhere and can be disabled. I think that current behaviou is ok, because validator return validation result as it is here https://w3c.github.io/csvw/tests/reports/index.html (PASSED, WARNING - validation with just warnings, ERROR - validation with errors). CSV on the Web doesn't support warnings/errors for these strict rules, so disabling them can make validation result PASSED for CSV on the Web test cases.

**Comment by jakubklimek** [comment]
OK
